/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2015 Aleksandar Cvetković
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package gui.filters;

/**
 *
 * @author Aleksandar Cvetković <arcvetkovic@gmail.com>
 */
public class MatchType extends javax.swing.JPanel {

    /**
     * Creates new form MatchType
     */
    public MatchType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTop = new javax.swing.JPanel();
        labelCompetitions = new javax.swing.JLabel();
        labelFriendlies = new javax.swing.JLabel();
        panelBottom = new javax.swing.JPanel();
        panelCompetitions = new javax.swing.JPanel();
        cbAllCompetitions = new javax.swing.JCheckBox();
        panelLeague = new javax.swing.JPanel();
        cbLeague = new javax.swing.JCheckBox();
        cbQualification = new javax.swing.JCheckBox();
        panelNationalCup = new javax.swing.JPanel();
        cbNationalCup = new javax.swing.JCheckBox();
        cbNationalEmerald = new javax.swing.JCheckBox();
        cbNationalRuby = new javax.swing.JCheckBox();
        cbNationalSapphire = new javax.swing.JCheckBox();
        cbNationalConsolation = new javax.swing.JCheckBox();
        panelDivisionalCup = new javax.swing.JPanel();
        cbDivisionalCup = new javax.swing.JCheckBox();
        cbDivisionalEmerald = new javax.swing.JCheckBox();
        cbDivisionalRuby = new javax.swing.JCheckBox();
        cbDivisionalSapphire = new javax.swing.JCheckBox();
        cbDivisionalConsolation = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        labelDivisional = new javax.swing.JLabel();
        cbLevel7 = new javax.swing.JCheckBox();
        cbLevel8 = new javax.swing.JCheckBox();
        cbLevel9 = new javax.swing.JCheckBox();
        panelHattrickMasters = new javax.swing.JPanel();
        cbHattrickMasters = new javax.swing.JCheckBox();
        panelFriendlies = new javax.swing.JPanel();
        cbAllFriendlies = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());

        panelTop.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTop.setMaximumSize(new java.awt.Dimension(32767, 30));
        panelTop.setMinimumSize(new java.awt.Dimension(100, 30));
        panelTop.setPreferredSize(new java.awt.Dimension(100, 30));
        panelTop.setLayout(new java.awt.GridLayout(1, 2));

        labelCompetitions.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelCompetitions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCompetitions.setText("Competitions");
        labelCompetitions.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelTop.add(labelCompetitions);

        labelFriendlies.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelFriendlies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFriendlies.setText("Friendlies");
        labelFriendlies.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelTop.add(labelFriendlies);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(panelTop, gridBagConstraints);

        panelBottom.setLayout(new java.awt.CardLayout());

        panelCompetitions.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbAllCompetitions.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbAllCompetitions.setSelected(true);
        cbAllCompetitions.setText("All competitions");

        panelLeague.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "League", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 0, 12))); // NOI18N

        cbLeague.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbLeague.setSelected(true);
        cbLeague.setText("League");

        cbQualification.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbQualification.setSelected(true);
        cbQualification.setText("Qualification");

        javax.swing.GroupLayout panelLeagueLayout = new javax.swing.GroupLayout(panelLeague);
        panelLeague.setLayout(panelLeagueLayout);
        panelLeagueLayout.setHorizontalGroup(
            panelLeagueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeagueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLeagueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbLeague)
                    .addComponent(cbQualification))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLeagueLayout.setVerticalGroup(
            panelLeagueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeagueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbLeague)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbQualification)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelNationalCup.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "National Cup", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 0, 12))); // NOI18N

        cbNationalCup.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbNationalCup.setSelected(true);
        cbNationalCup.setText("National Cup");

        cbNationalEmerald.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbNationalEmerald.setSelected(true);
        cbNationalEmerald.setText("Emerald Challenger Cup");

        cbNationalRuby.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbNationalRuby.setSelected(true);
        cbNationalRuby.setText("Ruby Challenger Cup");

        cbNationalSapphire.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbNationalSapphire.setSelected(true);
        cbNationalSapphire.setText("Sapphire Challenger Cup");

        cbNationalConsolation.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbNationalConsolation.setSelected(true);
        cbNationalConsolation.setText("Consolation Cup");

        javax.swing.GroupLayout panelNationalCupLayout = new javax.swing.GroupLayout(panelNationalCup);
        panelNationalCup.setLayout(panelNationalCupLayout);
        panelNationalCupLayout.setHorizontalGroup(
            panelNationalCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNationalCupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNationalCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbNationalCup)
                    .addComponent(cbNationalEmerald)
                    .addComponent(cbNationalRuby)
                    .addComponent(cbNationalSapphire)
                    .addComponent(cbNationalConsolation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNationalCupLayout.setVerticalGroup(
            panelNationalCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNationalCupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbNationalCup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNationalEmerald)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNationalRuby)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNationalSapphire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNationalConsolation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDivisionalCup.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Divisional Cup", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 0, 12))); // NOI18N

        cbDivisionalCup.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbDivisionalCup.setSelected(true);
        cbDivisionalCup.setText("Divisional Cup");

        cbDivisionalEmerald.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbDivisionalEmerald.setSelected(true);
        cbDivisionalEmerald.setText("Emerald Challenger Cup");

        cbDivisionalRuby.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbDivisionalRuby.setSelected(true);
        cbDivisionalRuby.setText("Ruby Challenger Cup");

        cbDivisionalSapphire.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbDivisionalSapphire.setSelected(true);
        cbDivisionalSapphire.setText("Sapphire Challenger Cup");

        cbDivisionalConsolation.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbDivisionalConsolation.setSelected(true);
        cbDivisionalConsolation.setText("Consolation Cup");

        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 1));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 1));

        labelDivisional.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelDivisional.setText("Divisional Cup levels:");

        cbLevel7.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbLevel7.setSelected(true);
        cbLevel7.setText("7");

        cbLevel8.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbLevel8.setSelected(true);
        cbLevel8.setText("8");

        cbLevel9.setSelected(true);
        cbLevel9.setText("9");

        javax.swing.GroupLayout panelDivisionalCupLayout = new javax.swing.GroupLayout(panelDivisionalCup);
        panelDivisionalCup.setLayout(panelDivisionalCupLayout);
        panelDivisionalCupLayout.setHorizontalGroup(
            panelDivisionalCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDivisionalCupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDivisionalCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDivisionalCupLayout.createSequentialGroup()
                        .addGroup(panelDivisionalCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDivisionalCup)
                            .addComponent(cbDivisionalEmerald)
                            .addComponent(cbDivisionalRuby)
                            .addComponent(cbDivisionalSapphire)
                            .addComponent(cbDivisionalConsolation)
                            .addGroup(panelDivisionalCupLayout.createSequentialGroup()
                                .addComponent(labelDivisional)
                                .addGap(18, 18, 18)
                                .addComponent(cbLevel7)
                                .addGap(18, 18, 18)
                                .addComponent(cbLevel8)
                                .addGap(18, 18, 18)
                                .addComponent(cbLevel9)))
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDivisionalCupLayout.setVerticalGroup(
            panelDivisionalCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDivisionalCupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbDivisionalCup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDivisionalEmerald)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDivisionalRuby)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDivisionalSapphire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDivisionalConsolation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDivisionalCupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLevel7)
                    .addComponent(labelDivisional)
                    .addComponent(cbLevel8)
                    .addComponent(cbLevel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHattrickMasters.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Hattrick Masters", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 0, 12))); // NOI18N

        cbHattrickMasters.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbHattrickMasters.setSelected(true);
        cbHattrickMasters.setText("Hattrick Masters");

        javax.swing.GroupLayout panelHattrickMastersLayout = new javax.swing.GroupLayout(panelHattrickMasters);
        panelHattrickMasters.setLayout(panelHattrickMastersLayout);
        panelHattrickMastersLayout.setHorizontalGroup(
            panelHattrickMastersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHattrickMastersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbHattrickMasters)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHattrickMastersLayout.setVerticalGroup(
            panelHattrickMastersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHattrickMastersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbHattrickMasters)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCompetitionsLayout = new javax.swing.GroupLayout(panelCompetitions);
        panelCompetitions.setLayout(panelCompetitionsLayout);
        panelCompetitionsLayout.setHorizontalGroup(
            panelCompetitionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompetitionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCompetitionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLeague, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNationalCup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDivisionalCup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCompetitionsLayout.createSequentialGroup()
                        .addComponent(cbAllCompetitions)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelHattrickMasters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCompetitionsLayout.setVerticalGroup(
            panelCompetitionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompetitionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAllCompetitions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLeague, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNationalCup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDivisionalCup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHattrickMasters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBottom.add(panelCompetitions, "card2");

        panelFriendlies.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbAllFriendlies.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbAllFriendlies.setText("All friendlies");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Friendlies", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 0, 12))); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jCheckBox1.setText("Friendly (normal rules)");

        jCheckBox2.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jCheckBox2.setText("Friendly (cup rules)");

        jCheckBox3.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jCheckBox3.setText("International friendly (normal rules)");

        jCheckBox4.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jCheckBox4.setText("International friendly (cup rules)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFriendliesLayout = new javax.swing.GroupLayout(panelFriendlies);
        panelFriendlies.setLayout(panelFriendliesLayout);
        panelFriendliesLayout.setHorizontalGroup(
            panelFriendliesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFriendliesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFriendliesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFriendliesLayout.createSequentialGroup()
                        .addComponent(cbAllFriendlies)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFriendliesLayout.setVerticalGroup(
            panelFriendliesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFriendliesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAllFriendlies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        panelBottom.add(panelFriendlies, "card3");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(panelBottom, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAllCompetitions;
    private javax.swing.JCheckBox cbAllFriendlies;
    private javax.swing.JCheckBox cbDivisionalConsolation;
    private javax.swing.JCheckBox cbDivisionalCup;
    private javax.swing.JCheckBox cbDivisionalEmerald;
    private javax.swing.JCheckBox cbDivisionalRuby;
    private javax.swing.JCheckBox cbDivisionalSapphire;
    private javax.swing.JCheckBox cbHattrickMasters;
    private javax.swing.JCheckBox cbLeague;
    private javax.swing.JCheckBox cbLevel7;
    private javax.swing.JCheckBox cbLevel8;
    private javax.swing.JCheckBox cbLevel9;
    private javax.swing.JCheckBox cbNationalConsolation;
    private javax.swing.JCheckBox cbNationalCup;
    private javax.swing.JCheckBox cbNationalEmerald;
    private javax.swing.JCheckBox cbNationalRuby;
    private javax.swing.JCheckBox cbNationalSapphire;
    private javax.swing.JCheckBox cbQualification;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCompetitions;
    private javax.swing.JLabel labelDivisional;
    private javax.swing.JLabel labelFriendlies;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelCompetitions;
    private javax.swing.JPanel panelDivisionalCup;
    private javax.swing.JPanel panelFriendlies;
    private javax.swing.JPanel panelHattrickMasters;
    private javax.swing.JPanel panelLeague;
    private javax.swing.JPanel panelNationalCup;
    private javax.swing.JPanel panelTop;
    // End of variables declaration//GEN-END:variables
}
