/*
 The MIT License (MIT)

 Copyright (c) 2015 Aleksandar Cvetković

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */
package htsquirrel.gui.menu;

import static htsquirrel.HTSquirrel.getCurrentTeam;
import static htsquirrel.HTSquirrel.getLanguage;
import static htsquirrel.HTSquirrel.getOrange;
import static htsquirrel.HTSquirrel.getTeams;
import static htsquirrel.HTSquirrel.hideSmallPages;
import static htsquirrel.HTSquirrel.setCurrentTeam;
import static htsquirrel.HTSquirrel.showDownload;
import static htsquirrel.HTSquirrel.showRecords;
import static htsquirrel.HTSquirrel.showSettings;
import static htsquirrel.HTSquirrel.showTeam;
import htsquirrel.translations.Translations;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Aleksandar Cvetković <arcvetkovic@gmail.com>
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeft = new javax.swing.JPanel();
        labelTeamName = new javax.swing.JLabel();
        labelSwitchTeam = new javax.swing.JLabel();
        panelRight = new javax.swing.JPanel();
        panelCenter = new javax.swing.JPanel();
        labelTeam = new javax.swing.JLabel();
        labelRecords = new javax.swing.JLabel();
        labelDownload = new javax.swing.JLabel();
        labelSettings = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(2147483647, 50));
        setLayout(new java.awt.BorderLayout());

        panelLeft.setBackground(new java.awt.Color(51, 51, 51));
        panelLeft.setMaximumSize(new java.awt.Dimension(480, 50));
        panelLeft.setMinimumSize(new java.awt.Dimension(480, 50));
        panelLeft.setPreferredSize(new java.awt.Dimension(480, 50));

        labelTeamName.setForeground(new java.awt.Color(255, 102, 0));
        labelTeamName.setText(" ");

        labelSwitchTeam.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        labelSwitchTeam.setForeground(new java.awt.Color(128, 128, 128));
        labelSwitchTeam.setText("switch team");
        labelSwitchTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSwitchTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSwitchTeamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTeamName)
                    .addComponent(labelSwitchTeam))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTeamName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSwitchTeam)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(panelLeft, java.awt.BorderLayout.LINE_START);

        panelRight.setBackground(new java.awt.Color(51, 51, 51));
        panelRight.setMaximumSize(new java.awt.Dimension(5, 50));
        panelRight.setMinimumSize(new java.awt.Dimension(5, 50));
        panelRight.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(panelRight, java.awt.BorderLayout.LINE_END);

        panelCenter.setBackground(new java.awt.Color(51, 51, 51));

        labelTeam.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        labelTeam.setForeground(new java.awt.Color(128, 128, 128));
        labelTeam.setText("TEAM");
        labelTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTeamMouseClicked(evt);
            }
        });

        labelRecords.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        labelRecords.setForeground(new java.awt.Color(128, 128, 128));
        labelRecords.setText("RECORDS");
        labelRecords.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRecordsMouseClicked(evt);
            }
        });

        labelDownload.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        labelDownload.setForeground(new java.awt.Color(128, 128, 128));
        labelDownload.setText("DOWNLOAD");
        labelDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelDownload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDownloadMouseClicked(evt);
            }
        });

        labelSettings.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        labelSettings.setForeground(new java.awt.Color(128, 128, 128));
        labelSettings.setText("SETTINGS");
        labelSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSettingsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTeam)
                .addGap(18, 18, 18)
                .addComponent(labelRecords)
                .addGap(18, 18, 18)
                .addComponent(labelDownload)
                .addGap(18, 18, 18)
                .addComponent(labelSettings)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTeam)
                    .addComponent(labelRecords)
                    .addComponent(labelDownload)
                    .addComponent(labelSettings))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(panelCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void labelTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTeamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelTeamMouseClicked

    private void labelRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRecordsMouseClicked
        labelTeam.setForeground(new java.awt.Color(128, 128, 128));
        labelRecords.setForeground(getOrange());
        labelDownload.setForeground(new java.awt.Color(128, 128, 128));
        labelSettings.setForeground(new java.awt.Color(128, 128, 128));
        hideSmallPages();
        showRecords();
    }//GEN-LAST:event_labelRecordsMouseClicked

    private void labelDownloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDownloadMouseClicked
        labelTeam.setForeground(new java.awt.Color(128, 128, 128));
        labelRecords.setForeground(new java.awt.Color(128, 128, 128));
        labelDownload.setForeground(getOrange());
        labelSettings.setForeground(new java.awt.Color(128, 128, 128));
        showDownload();
    }//GEN-LAST:event_labelDownloadMouseClicked

    private void labelSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSettingsMouseClicked
        labelTeam.setForeground(new java.awt.Color(128, 128, 128));
        labelRecords.setForeground(new java.awt.Color(128, 128, 128));
        labelDownload.setForeground(new java.awt.Color(128, 128, 128));
        labelSettings.setForeground(getOrange());
        showSettings();
    }//GEN-LAST:event_labelSettingsMouseClicked

    private void labelSwitchTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSwitchTeamMouseClicked
        if (getCurrentTeam().getTeamId() == getTeams().get(0).getTeamId()) {
            setCurrentTeam(getTeams().get(1));
        } else {
            setCurrentTeam(getTeams().get(0));
        }
        labelTeamName.setText(getCurrentTeam().getTeamName());
        labelTeam.setForeground(getOrange());
        labelRecords.setForeground(new java.awt.Color(128, 128, 128));
        labelDownload.setForeground(new java.awt.Color(128, 128, 128));
        labelSettings.setForeground(new java.awt.Color(128, 128, 128));
        showTeam();
    }//GEN-LAST:event_labelSwitchTeamMouseClicked

    public JLabel getLabelDownload() {
        return labelDownload;
    }

    public JLabel getLabelRecords() {
        return labelRecords;
    }

    public JLabel getLabelSettings() {
        return labelSettings;
    }

    public JLabel getLabelSwitchTeam() {
        return labelSwitchTeam;
    }

    public JLabel getLabelTeam() {
        return labelTeam;
    }

    public JLabel getLabelTeamName() {
        return labelTeamName;
    }

    public void refreshMenu() {
        Translations translations = new Translations();
        Properties properties = null;
        try {
            properties = translations.getTranslations(getLanguage());
            labelSwitchTeam.setText(properties.getProperty("menu_switch_team"));
            labelTeam.setText(properties.getProperty("menu_team"));
            labelRecords.setText(properties.getProperty("menu_records"));
            labelDownload.setText(properties.getProperty("menu_download"));
            labelSettings.setText(properties.getProperty("menu_settings"));
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        labelTeam.setForeground(new java.awt.Color(128, 128, 128));
        labelRecords.setForeground(new java.awt.Color(128, 128, 128));
        labelDownload.setForeground(new java.awt.Color(128, 128, 128));
        labelSettings.setForeground(new java.awt.Color(128, 128, 128));
        getLabelTeamName().setText(getCurrentTeam().getTeamName());
        if (getTeams().size() > 1) {
            getLabelSwitchTeam().setVisible(true);
        }
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDownload;
    private javax.swing.JLabel labelRecords;
    private javax.swing.JLabel labelSettings;
    private javax.swing.JLabel labelSwitchTeam;
    private javax.swing.JLabel labelTeam;
    private javax.swing.JLabel labelTeamName;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    // End of variables declaration//GEN-END:variables
}
