/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2015 Aleksandar Cvetković
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package htsquirrel.gui.filters;

/**
 *
 * @author Aleksandar Cvetković <arcvetkovic@gmail.com>
 */
public class Arena extends javax.swing.JPanel {

    /**
     * Creates new form Arena
     */
    public Arena() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelAll = new javax.swing.JPanel();
        panelVenue = new javax.swing.JPanel();
        cbHome = new javax.swing.JCheckBox();
        cbAway = new javax.swing.JCheckBox();
        panelSpectators = new javax.swing.JPanel();
        cbTotal = new javax.swing.JCheckBox();
        labelTotalFrom = new javax.swing.JLabel();
        sTotalFrom = new javax.swing.JSpinner();
        labelTotalTo = new javax.swing.JLabel();
        sTotalTo = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        cbByType = new javax.swing.JCheckBox();
        labelTerraces = new javax.swing.JLabel();
        labelTerracesFrom = new javax.swing.JLabel();
        sTerracesFrom = new javax.swing.JSpinner();
        labelTerracesTo = new javax.swing.JLabel();
        sTerracesTo = new javax.swing.JSpinner();
        labelBasic = new javax.swing.JLabel();
        labelBasicFrom = new javax.swing.JLabel();
        sBasicFrom = new javax.swing.JSpinner();
        labelBasicTo = new javax.swing.JLabel();
        sBasicTo = new javax.swing.JSpinner();
        labelRoof = new javax.swing.JLabel();
        labelRoofFrom = new javax.swing.JLabel();
        sRoofFrom = new javax.swing.JSpinner();
        labelRoofTo = new javax.swing.JLabel();
        sRoofTo = new javax.swing.JSpinner();
        labelVip = new javax.swing.JLabel();
        labelVipFrom = new javax.swing.JLabel();
        sVipFrom = new javax.swing.JSpinner();
        labelVipTo = new javax.swing.JLabel();
        sVipTo = new javax.swing.JSpinner();
        panelWeather = new javax.swing.JPanel();
        cbSunny = new javax.swing.JCheckBox();
        cbPartiallyCloudy = new javax.swing.JCheckBox();
        cbCloudy = new javax.swing.JCheckBox();
        cbRainy = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new java.awt.CardLayout());

        panelVenue.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Venue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 0, 12))); // NOI18N

        cbHome.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbHome.setSelected(true);
        cbHome.setText("Home");

        cbAway.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbAway.setSelected(true);
        cbAway.setText("Away");

        javax.swing.GroupLayout panelVenueLayout = new javax.swing.GroupLayout(panelVenue);
        panelVenue.setLayout(panelVenueLayout);
        panelVenueLayout.setHorizontalGroup(
            panelVenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbHome)
                    .addComponent(cbAway))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVenueLayout.setVerticalGroup(
            panelVenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAway))
        );

        panelSpectators.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Spectators", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 0, 12))); // NOI18N

        cbTotal.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbTotal.setSelected(true);
        cbTotal.setText("Total");

        labelTotalFrom.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelTotalFrom.setText("From:");

        sTotalFrom.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        labelTotalTo.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelTotalTo.setText("To:");

        sTotalTo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 1));
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 1));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 1));

        cbByType.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbByType.setText("By type");

        labelTerraces.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        labelTerraces.setText("Terraces");

        labelTerracesFrom.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelTerracesFrom.setText("From:");

        sTerracesFrom.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        labelTerracesTo.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelTerracesTo.setText("To:");

        sTerracesTo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        labelBasic.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        labelBasic.setText("Basic");

        labelBasicFrom.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelBasicFrom.setText("From:");

        sBasicFrom.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        labelBasicTo.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelBasicTo.setText("To:");

        sBasicTo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        labelRoof.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        labelRoof.setText("Roof");

        labelRoofFrom.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelRoofFrom.setText("From:");

        sRoofFrom.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        labelRoofTo.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelRoofTo.setText("To:");

        sRoofTo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        labelVip.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        labelVip.setText("VIP");

        labelVipFrom.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelVipFrom.setText("From:");

        sVipFrom.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        labelVipTo.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        labelVipTo.setText("To:");

        sVipTo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        javax.swing.GroupLayout panelSpectatorsLayout = new javax.swing.GroupLayout(panelSpectators);
        panelSpectators.setLayout(panelSpectatorsLayout);
        panelSpectatorsLayout.setHorizontalGroup(
            panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSpectatorsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSpectatorsLayout.createSequentialGroup()
                        .addGroup(panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSpectatorsLayout.createSequentialGroup()
                                .addComponent(labelTotalFrom)
                                .addGap(18, 18, 18)
                                .addComponent(sTotalFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelTotalTo)
                                .addGap(18, 18, 18)
                                .addComponent(sTotalTo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelBasic)
                            .addComponent(labelRoof)
                            .addGroup(panelSpectatorsLayout.createSequentialGroup()
                                .addGroup(panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSpectatorsLayout.createSequentialGroup()
                                        .addComponent(labelVipFrom)
                                        .addGap(18, 18, 18)
                                        .addComponent(sVipFrom))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSpectatorsLayout.createSequentialGroup()
                                        .addComponent(labelRoofFrom)
                                        .addGap(18, 18, 18)
                                        .addComponent(sRoofFrom))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSpectatorsLayout.createSequentialGroup()
                                        .addComponent(labelBasicFrom)
                                        .addGap(18, 18, 18)
                                        .addComponent(sBasicFrom))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSpectatorsLayout.createSequentialGroup()
                                        .addComponent(labelTerracesFrom)
                                        .addGap(18, 18, 18)
                                        .addComponent(sTerracesFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelSpectatorsLayout.createSequentialGroup()
                                        .addComponent(labelTerracesTo)
                                        .addGap(18, 18, 18)
                                        .addComponent(sTerracesTo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelSpectatorsLayout.createSequentialGroup()
                                        .addComponent(labelBasicTo)
                                        .addGap(18, 18, 18)
                                        .addComponent(sBasicTo))
                                    .addGroup(panelSpectatorsLayout.createSequentialGroup()
                                        .addComponent(labelRoofTo)
                                        .addGap(18, 18, 18)
                                        .addComponent(sRoofTo))
                                    .addGroup(panelSpectatorsLayout.createSequentialGroup()
                                        .addComponent(labelVipTo)
                                        .addGap(18, 18, 18)
                                        .addComponent(sVipTo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cbTotal)
                            .addComponent(labelVip)
                            .addComponent(cbByType)
                            .addComponent(labelTerraces))
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSpectatorsLayout.setVerticalGroup(
            panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSpectatorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalFrom)
                    .addComponent(sTotalFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotalTo)
                    .addComponent(sTotalTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbByType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTerraces)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTerracesFrom)
                    .addComponent(sTerracesFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTerracesTo)
                    .addComponent(sTerracesTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBasic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBasicFrom)
                    .addComponent(sBasicFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBasicTo)
                    .addComponent(sBasicTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRoof)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRoofFrom)
                    .addComponent(sRoofFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRoofTo)
                    .addComponent(sRoofTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelVip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVipFrom)
                    .addComponent(sVipFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVipTo)
                    .addComponent(sVipTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelWeather.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Weather", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 0, 12))); // NOI18N

        cbSunny.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbSunny.setSelected(true);
        cbSunny.setText("Sunny");

        cbPartiallyCloudy.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbPartiallyCloudy.setSelected(true);
        cbPartiallyCloudy.setText("Partially cloudy");

        cbCloudy.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbCloudy.setSelected(true);
        cbCloudy.setText("Cloudy");

        cbRainy.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        cbRainy.setSelected(true);
        cbRainy.setText("Rainy");

        javax.swing.GroupLayout panelWeatherLayout = new javax.swing.GroupLayout(panelWeather);
        panelWeather.setLayout(panelWeatherLayout);
        panelWeatherLayout.setHorizontalGroup(
            panelWeatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWeatherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWeatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSunny)
                    .addComponent(cbPartiallyCloudy)
                    .addComponent(cbCloudy)
                    .addComponent(cbRainy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelWeatherLayout.setVerticalGroup(
            panelWeatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWeatherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbSunny)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPartiallyCloudy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCloudy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRainy))
        );

        javax.swing.GroupLayout panelAllLayout = new javax.swing.GroupLayout(panelAll);
        panelAll.setLayout(panelAllLayout);
        panelAllLayout.setHorizontalGroup(
            panelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAllLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelVenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSpectators, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWeather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAllLayout.setVerticalGroup(
            panelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSpectators, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelWeather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelAll);

        add(jScrollPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAway;
    private javax.swing.JCheckBox cbByType;
    private javax.swing.JCheckBox cbCloudy;
    private javax.swing.JCheckBox cbHome;
    private javax.swing.JCheckBox cbPartiallyCloudy;
    private javax.swing.JCheckBox cbRainy;
    private javax.swing.JCheckBox cbSunny;
    private javax.swing.JCheckBox cbTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBasic;
    private javax.swing.JLabel labelBasicFrom;
    private javax.swing.JLabel labelBasicTo;
    private javax.swing.JLabel labelRoof;
    private javax.swing.JLabel labelRoofFrom;
    private javax.swing.JLabel labelRoofTo;
    private javax.swing.JLabel labelTerraces;
    private javax.swing.JLabel labelTerracesFrom;
    private javax.swing.JLabel labelTerracesTo;
    private javax.swing.JLabel labelTotalFrom;
    private javax.swing.JLabel labelTotalTo;
    private javax.swing.JLabel labelVip;
    private javax.swing.JLabel labelVipFrom;
    private javax.swing.JLabel labelVipTo;
    private javax.swing.JPanel panelAll;
    private javax.swing.JPanel panelSpectators;
    private javax.swing.JPanel panelVenue;
    private javax.swing.JPanel panelWeather;
    private javax.swing.JSpinner sBasicFrom;
    private javax.swing.JSpinner sBasicTo;
    private javax.swing.JSpinner sRoofFrom;
    private javax.swing.JSpinner sRoofTo;
    private javax.swing.JSpinner sTerracesFrom;
    private javax.swing.JSpinner sTerracesTo;
    private javax.swing.JSpinner sTotalFrom;
    private javax.swing.JSpinner sTotalTo;
    private javax.swing.JSpinner sVipFrom;
    private javax.swing.JSpinner sVipTo;
    // End of variables declaration//GEN-END:variables
}
