CREATE TABLE BOOKINGS (
    MATCH_ID BIGINT,
    TEAM_ID INT,
    BOOKING_INDEX INT,
    BOOKING_PLAYER_ID INT,
    BOOKING_PLAYER_NAME VARCHAR(255),
    BOOKING_TEAM_ID INT,
    BOOKING_TYPE INT,
    BOOKING_MINUTE INT
)
