CREATE TABLE EVENTS (
    MATCH_ID BIGINT,
    TEAM_ID INT,
    EVENT_INDEX INT,
    EVENT_MINUTE INT,
    EVENT_TYPE INT,
    EVENT_VARIATION INT,
    EVENT_SUBJECT_TEAM_ID INT,
    EVENT_SUBJECT_PLAYER_ID INT,
    EVENT_OBJECT_PLAYER_ID INT,
    EVENT_TEXT VARCHAR(4000)
)
