CREATE TABLE INJURIES (
    MATCH_ID BIGINT,
    TEAM_ID INT,
    INJURY_INDEX INT,
    INJURY_PLAYER_ID INT,
    INJURY_PLAYER_NAME VARCHAR(255),
    INJURY_TEAM_ID INT,
    INJURY_TYPE INT,
    INJURY_MINUTE INT
)
