CREATE TABLE LINEUPS (
    MATCH_ID BIGINT,
    TEAM_ID INT,
    PLAYER_ID INT,
    ROLE_ID INT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    NICK_NAME VARCHAR(255),
    BEHAVIOUR_ID INT,
    RATING_STARS DECIMAL(20, 2),
    RATING_STARS_END DECIMAL(20, 2)
)
