CREATE TABLE MATCHES (
    MATCH_ID BIGINT,
    TEAM_ID INT,
    TEAM_NAME VARCHAR(255),
    OPPONENT_TEAM_ID INT,
    OPPONENT_TEAM_NAME VARCHAR(255),
    VENUE VARCHAR(255),
    MATCH_DATE TIMESTAMP,
    SEASON INT,
    MATCH_TYPE INT,
    MATCH_CONTEXT_ID INT,
    CUP_LEVEL INT,
    CUP_LEVEL_INDEX INT,
    GOALS_FOR INT,
    GOALS_AGAINST INT
)
