CREATE TABLE SUBSTITUTIONS (
    MATCH_ID BIGINT,
    TEAM_ID INT,
    SUBJECT_PLAYER_ID INT,
    OBJECT_PLAYER_ID INT,
    ORDER_TYPE INT,
    NEW_POSITION INT,
    BEHAVIOUR_ID INT,
    MATCH_MINUTE INT
)
