CREATE TABLE TRANSFERS (
    TEAM_ID INT,
    TRANSFER_ID INT,
    DEADLINE TIMESTAMP,
    PLAYER_ID INT,
    PLAYER_NAME VARCHAR(255),
    TSI INT,
    TRANSFER_TYPE VARCHAR(255),
    BUYER_TEAM_ID INT,
    BUYER_TEAM_NAME VARCHAR(255),
    SELLER_TEAM_ID INT,
    SELLER_TEAM_NAME VARCHAR(255),
    PRICE INT
)
