/*
 The MIT License (MIT)

 Copyright (c) 2015 Aleksandar Cvetković

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */
package htsquirrel.gui.pages.matchfilter;

/**
 *
 * @author Aleksandar Cvetković <arcvetkovic@gmail.com>
 */
public class ArenaGeneral extends javax.swing.JPanel {

    /**
     * Creates new form ArenaBase
     */
    public ArenaGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVenue = new javax.swing.JPanel();
        checkBoxHome = new javax.swing.JCheckBox();
        checkBoxAway = new javax.swing.JCheckBox();
        panelSpectators = new javax.swing.JPanel();
        labelFrom = new javax.swing.JLabel();
        spinnerFrom = new javax.swing.JSpinner();
        labelTo = new javax.swing.JLabel();
        spinnerTo = new javax.swing.JSpinner();
        panelWeather = new javax.swing.JPanel();
        checkBoxSunny = new javax.swing.JCheckBox();
        checkBoxPartiallyCloudy = new javax.swing.JCheckBox();
        checkBoxOvercast = new javax.swing.JCheckBox();
        checkBoxRain = new javax.swing.JCheckBox();

        setBorder(null);

        panelVenue.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Venue"));

        checkBoxHome.setText("Home");

        checkBoxAway.setText("Away");

        javax.swing.GroupLayout panelVenueLayout = new javax.swing.GroupLayout(panelVenue);
        panelVenue.setLayout(panelVenueLayout);
        panelVenueLayout.setHorizontalGroup(
            panelVenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxHome)
                    .addComponent(checkBoxAway))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVenueLayout.setVerticalGroup(
            panelVenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVenueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxAway)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSpectators.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Spectators"));

        labelFrom.setText("From:");

        spinnerFrom.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        labelTo.setText("To:");

        spinnerTo.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1000)));

        javax.swing.GroupLayout panelSpectatorsLayout = new javax.swing.GroupLayout(panelSpectators);
        panelSpectators.setLayout(panelSpectatorsLayout);
        panelSpectatorsLayout.setHorizontalGroup(
            panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSpectatorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFrom)
                .addGap(18, 18, 18)
                .addComponent(spinnerFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTo)
                .addGap(18, 18, 18)
                .addComponent(spinnerTo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        panelSpectatorsLayout.setVerticalGroup(
            panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSpectatorsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSpectatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFrom)
                    .addComponent(labelTo)
                    .addComponent(spinnerTo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelWeather.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Weather"));

        checkBoxSunny.setText("Sunny");

        checkBoxPartiallyCloudy.setText("Partially cloudy");

        checkBoxOvercast.setText("Overcast");

        checkBoxRain.setText("Rain");

        javax.swing.GroupLayout panelWeatherLayout = new javax.swing.GroupLayout(panelWeather);
        panelWeather.setLayout(panelWeatherLayout);
        panelWeatherLayout.setHorizontalGroup(
            panelWeatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWeatherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWeatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxSunny)
                    .addComponent(checkBoxPartiallyCloudy)
                    .addComponent(checkBoxOvercast)
                    .addComponent(checkBoxRain))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelWeatherLayout.setVerticalGroup(
            panelWeatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWeatherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxSunny)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxPartiallyCloudy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxOvercast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxRain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelVenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSpectators, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWeather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSpectators, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelWeather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxAway;
    private javax.swing.JCheckBox checkBoxHome;
    private javax.swing.JCheckBox checkBoxOvercast;
    private javax.swing.JCheckBox checkBoxPartiallyCloudy;
    private javax.swing.JCheckBox checkBoxRain;
    private javax.swing.JCheckBox checkBoxSunny;
    private javax.swing.JLabel labelFrom;
    private javax.swing.JLabel labelTo;
    private javax.swing.JPanel panelSpectators;
    private javax.swing.JPanel panelVenue;
    private javax.swing.JPanel panelWeather;
    private javax.swing.JSpinner spinnerFrom;
    private javax.swing.JSpinner spinnerTo;
    // End of variables declaration//GEN-END:variables
}
