/*
 The MIT License (MIT)

 Copyright (c) 2015 Aleksandar Cvetković

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */
package htsquirrel.gui.pages.matchfilter;

/**
 *
 * @author Aleksandar Cvetković <arcvetkovic@gmail.com>
 */
public class Formation extends javax.swing.JPanel {

    /**
     * Creates new form Formation
     */
    public Formation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTop = new javax.swing.JPanel();
        panelLeft = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        panelRight = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        panelBottom = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        panelBase = new javax.swing.JPanel();
        formationTeam = new htsquirrel.gui.pages.matchfilter.FormationBase();
        formationOpponent = new htsquirrel.gui.pages.matchfilter.FormationBase();

        setLayout(new java.awt.GridBagLayout());

        panelTop.setMaximumSize(new java.awt.Dimension(32767, 50));
        panelTop.setMinimumSize(new java.awt.Dimension(100, 50));
        panelTop.setPreferredSize(new java.awt.Dimension(400, 50));
        panelTop.setLayout(new java.awt.GridLayout());

        panelLeft.setLayout(new java.awt.GridBagLayout());

        jToggleButton1.setSelected(true);
        jToggleButton1.setText("Team");
        jToggleButton1.setMaximumSize(new java.awt.Dimension(180, 27));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(180, 27));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(180, 27));
        panelLeft.add(jToggleButton1, new java.awt.GridBagConstraints());

        panelTop.add(panelLeft);

        panelRight.setLayout(new java.awt.GridBagLayout());

        jToggleButton2.setText("Opponent");
        jToggleButton2.setMaximumSize(new java.awt.Dimension(180, 27));
        jToggleButton2.setMinimumSize(new java.awt.Dimension(180, 27));
        jToggleButton2.setPreferredSize(new java.awt.Dimension(180, 27));
        panelRight.add(jToggleButton2, new java.awt.GridBagConstraints());

        panelTop.add(panelRight);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(panelTop, gridBagConstraints);

        scrollPane.setBorder(null);

        panelBase.setLayout(new java.awt.CardLayout());
        panelBase.add(formationTeam, "card2");
        panelBase.add(formationOpponent, "card3");

        scrollPane.setViewportView(panelBase);

        javax.swing.GroupLayout panelBottomLayout = new javax.swing.GroupLayout(panelBottom);
        panelBottom.setLayout(panelBottomLayout);
        panelBottomLayout.setHorizontalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
        );
        panelBottomLayout.setVerticalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(panelBottom, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private htsquirrel.gui.pages.matchfilter.FormationBase formationOpponent;
    private htsquirrel.gui.pages.matchfilter.FormationBase formationTeam;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelTop;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
