SELECT
    SUM(CASE WHEN (GOALS_FOR > GOALS_AGAINST) THEN 1 ELSE 0 END) AS W,
    SUM(CASE WHEN (GOALS_FOR = GOALS_AGAINST) THEN 1 ELSE 0 END) AS D,
    SUM(CASE WHEN (GOALS_FOR < GOALS_AGAINST) THEN 1 ELSE 0 END) AS L,
    SUM(GOALS_FOR) AS GF,
    SUM(GOALS_AGAINST) AS GA
FROM
    MATCHES_EXTENDED
