CREATE TABLE REFEREES (
    MATCH_ID BIGINT,
    TEAM_ID INT,
    REFEREE_ROLE INT,
    REFEREE_ID INT,
    REFEREE_NAME VARCHAR(255),
    REFEREE_COUNTRY_ID INT,
    REFEREE_COUNTRY_NAME VARCHAR(255),
    REFEREE_TEAM_ID INT,
    REFEREE_TEAM_NAME VARCHAR(255)
)
