CREATE TABLE GOALS (
    MATCH_ID BIGINT,
    TEAM_ID INT,
    GOAL_INDEX INT,
    GOAL_PLAYER_ID INT,
    GOAL_PLAYER_NAME VARCHAR(255),
    GOAL_TEAM_ID INT,
    GOAL_GOALS_FOR INT,
    GOAL_GOALS_AGAINST INT,
    GOAL_MINUTE INT
)
