INSERT INTO TRANSFERS VALUES (
    VALUE_TEAM_ID,
    VALUE_TRANSFER_ID,
    'VALUE_DEADLINE',
    VALUE_PLAYER_ID,
    'VALUE_PLAYER_NAME',
    VALUE_TSI,
    'VALUE_TRANSFER_TYPE',
    VALUE_BUYER_TEAM_ID,
    'VALUE_BUYER_TEAM_NAME',
    VALUE_SELLER_TEAM_ID,
    'VALUE_SELLER_TEAM_NAME',
    VALUE_PRICE
)
