INSERT INTO BOOKINGS VALUES (
    VALUE_MATCH_ID,
    VALUE_TEAM_ID,
    VALUE_BOOKING_INDEX,
    VALUE_BOOKING_PLAYER_ID,
    'VALUE_BOOKING_PLAYER_NAME',
    VALUE_BOOKING_TEAM_ID,
    VALUE_BOOKING_TYPE,
    VALUE_BOOKING_MINUTE
)
