INSERT INTO MATCHES VALUES (
VALUE_MATCH_ID,
VALUE_TEAM_ID,
'VALUE_TEAM_NAME',
VALUE_OPPONENT_TEAM_ID,
'VALUE_OPPONENT_TEAM_NAME',
'VALUE_VENUE',
'VALUE_MATCH_DATE',
VALUE_SEASON,
VALUE_MATCH_TYPE,
VALUE_MATCH_CONTEXT_ID,
VALUE_CUP_LEVEL,
VALUE_CUP_LEVEL_INDEX,
VALUE_GOALS_FOR,
VALUE_GOALS_AGAINST
)
