INSERT INTO GOALS VALUES (
    VALUE_MATCH_ID,
    VALUE_TEAM_ID,
    VALUE_GOAL_INDEX,
    VALUE_GOAL_PLAYER_ID,
    'VALUE_GOAL_PLAYER_NAME',
    VALUE_GOAL_TEAM_ID,
    VALUE_GOAL_GOALS_FOR,
    VALUE_GOAL_GOALS_AGAINST,
    VALUE_GOAL_MINUTE
)
