INSERT INTO REFEREES VALUES (
    VALUE_MATCH_ID,
    VALUE_TEAM_ID,
    VALUE_REFEREE_ROLE,
    VALUE_REFEREE_ID,
    'VALUE_REFEREE_NAME',
    VALUE_REFEREE_COUNTRY_ID,
    'VALUE_REFEREE_COUNTRY_NAME',
    VALUE_REFEREE_TEAM_ID,
    'VALUE_REFEREE_TEAM_NAME'
)
