INSERT INTO EVENTS VALUES (
    VALUE_MATCH_ID,
    VALUE_TEAM_ID,
    VALUE_EVENT_INDEX,
    VALUE_EVENT_MINUTE,
    VALUE_EVENT_TYPE,
    VALUE_EVENT_VARIATION,
    VALUE_EVENT_SUBJECT_TEAM_ID,
    VALUE_EVENT_SUBJECT_PLAYER_ID,
    VALUE_EVENT_OBJECT_PLAYER_ID,
    'VALUE_EVENT_TEXT'
)
