INSERT INTO INJURIES VALUES (
    VALUE_MATCH_ID,
    VALUE_TEAM_ID,
    VALUE_INJURY_INDEX,
    VALUE_INJURY_PLAYER_ID,
    'VALUE_INJURY_PLAYER_NAME',
    VALUE_INJURY_TEAM_ID,
    VALUE_INJURY_TYPE,
    VALUE_INJURY_MINUTE
)
