WHERE
    TEAM_ID = V_TEAM_ID
    AND (MATCH_TYPE = V_MATCH_TYPE_L
        OR MATCH_TYPE = V_MATCH_TYPE_Q
        OR MATCH_TYPE = V_MATCH_TYPE_HM
        OR MATCH_TYPE = V_MATCH_TYPE_FN
        OR MATCH_TYPE = V_MATCH_TYPE_FC
        OR MATCH_TYPE = V_MATCH_TYPE_IFN
        OR MATCH_TYPE = V_MATCH_TYPE_IFC
        OR (CUP_LEAGUE_LEVEL = 0 AND CUP_LEVEL = V_CUP_LEVEL_N)
        OR (CUP_LEAGUE_LEVEL = 0 AND CUP_LEVEL = 2 AND CUP_LEVEL_INDEX = V_CUP_LEVEL_INDEX_NE)
        OR (CUP_LEAGUE_LEVEL = 0 AND CUP_LEVEL = 2 AND CUP_LEVEL_INDEX = V_CUP_LEVEL_INDEX_NR)
        OR (CUP_LEAGUE_LEVEL = 0 AND CUP_LEVEL = 2 AND CUP_LEVEL_INDEX = V_CUP_LEVEL_INDEX_NS)
        OR (CUP_LEAGUE_LEVEL = 0 AND CUP_LEVEL = V_CUP_LEVEL_NC)
        OR (CUP_LEAGUE_LEVEL IN V_CUP_LEAGUE_LEVEL_D AND CUP_LEVEL = V_CUP_LEVEL_D)
        OR (CUP_LEAGUE_LEVEL IN V_CUP_LEAGUE_LEVEL_D AND CUP_LEVEL = 2 AND CUP_LEVEL_INDEX = V_CUP_LEVEL_INDEX_DE)
        OR (CUP_LEAGUE_LEVEL IN V_CUP_LEAGUE_LEVEL_D AND CUP_LEVEL = 2 AND CUP_LEVEL_INDEX = V_CUP_LEVEL_INDEX_DR)
        OR (CUP_LEAGUE_LEVEL IN V_CUP_LEAGUE_LEVEL_D AND CUP_LEVEL = 2 AND CUP_LEVEL_INDEX = V_CUP_LEVEL_INDEX_DS)
        OR (CUP_LEAGUE_LEVEL IN V_CUP_LEAGUE_LEVEL_D AND CUP_LEVEL = V_CUP_LEVEL_DC))
    AND SEASON BETWEEN V_SEASON_FROM AND V_SEASON_TO
    AND MATCH_DATE BETWEEN 'V_MATCH_DATE_FROM' AND 'V_MATCH_DATE_TO'
    AND LEAGUE_LEVEL BETWEEN V_LEAGUE_LEVEL_FROM AND V_LEAGUE_LEVEL_TO
    AND LEAGUE_LEVEL_UNIT_NAME LIKE ('V_LEAGUE_LEVEL_UNIT_NAME')
    AND VENUE IN V_VENUE
    AND SOLD_TOTAL BETWEEN V_SOLD_TOTAL_FROM AND V_SOLD_TOTAL_TO
    AND SOLD_TERRACES BETWEEN V_SOLD_TERRACES_FROM AND V_SOLD_TERRACES_TO
    AND SOLD_BASIC BETWEEN V_SOLD_BASIC_FROM AND V_SOLD_BASIC_TO
    AND SOLD_ROOF BETWEEN V_SOLD_ROOF_FROM AND V_SOLD_ROOF_TO
    AND SOLD_VIP BETWEEN V_SOLD_VIP_FROM AND V_SOLD_VIP_TO
    AND WEATHER_ID IN V_WEATHER_ID
