INSERT INTO LEAGUES
SELECT
    T1.TEAM_ID,
    T1.SEASON,
    T2.LEAGUE_LEVEL_UNIT_ID,
    T2.LEAGUE_LEVEL,
    T2.LEAGUE_LEVEL_UNIT_NAME
FROM
    LEAGUE_IDS T1
INNER JOIN
    LEAGUE_NAMES T2
ON
    T1.MATCH_CONTEXT_ID = T2.LEAGUE_LEVEL_UNIT_ID
ORDER BY
    T1.TEAM_ID,
    T1.SEASON
